Repository axolotl-ai-cloud/axolotl, pull requests merged in 2023-08, with the labels that each got.

#285 Attention mask and position id fixes for packing
  README.md
  requirements.txt
  scripts/finetune.py
  src/axolotl/datasets.py
  src/axolotl/monkeypatch/llama_attn_hijack_flash.py
  src/axolotl/monkeypatch/llama_attn_hijack_xformers.py
  src/axolotl/monkeypatch/llama_expand_mask.py
  src/axolotl/monkeypatch/utils.py
  src/axolotl/prompt_strategies/alpaca_w_system.py
  src/axolotl/prompters.py
  src/axolotl/utils/collators.py
  src/axolotl/utils/data.py
  src/axolotl/utils/dataloader.py
  src/axolotl/utils/distributed.py
  src/axolotl/utils/models.py
  src/axolotl/utils/trainer.py
  src/axolotl/utils/validation.py
  tests/monkeypatch/test_llama_attn_hijack_flash.py
  tests/test_expand_mask.py
  tests/test_packed_dataset.py
  tests/test_prompt_tokenizers.py
  tests/test_prompters.py
  tests/test_validation.py
Labels: enhancement

#126 add templates, CoC and contributing guide
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_simple.md
  .github/SECURITY.md
  .github/SUPPORT.md
  README.md
Labels: awaiting_rebase

#450 add missing positional arg
  src/axolotl/utils/trainer.py
Labels: bug
