Repository axolotl-ai-cloud/axolotl, pull requests merged in 2024-10, with the labels that each got.

#1952 fix(log): update perplexity log to clarify from eval split
  src/axolotl/utils/callbacks/__init__.py
Labels: ready to merge

#1941 Fix type annotations in relora.py
  src/axolotl/monkeypatch/relora.py
Labels: ready to merge

#1939 Comet integration
  .isort.cfg
  README.md
  docs/config.qmd
  src/axolotl/cli/__init__.py
  src/axolotl/core/trainer_builder.py
  src/axolotl/utils/__init__.py
  src/axolotl/utils/callbacks/__init__.py
  src/axolotl/utils/callbacks/comet_.py
  src/axolotl/utils/comet_.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  tests/test_validation.py
Labels: ready to merge

#1927 Fixing/Adding Mistral Templates
  src/axolotl/utils/chat_templates.py
Labels: ready to merge

#1912 Add Support for `revision` Dataset Parameter to specify reading from Huggingface Dataset Revision
  docs/config.qmd
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/rl.py
  src/axolotl/utils/data/sft.py
  tests/test_datasets.py
Labels: ready to merge

#1961 Add MLFlow run name option in config
  docs/config.qmd
  src/axolotl/core/trainer_builder.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
Labels: ready to merge

#1958 Handle image input as string paths for MMLMs
  src/axolotl/utils/collators/mm_chat.py
Labels: ready to merge

#1964 update hf deps
  requirements.txt
  src/axolotl/utils/trainer.py
Labels: ready to merge

#1951 fix(doc): update eval causal lm metrics doc to add perplexity
  docs/config.qmd
Labels: ready to merge

#1934 Add support for qwen 2.5 chat template
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
Labels: ready to merge

#1904 wip add new proposed message structure
  requirements_env.txt
  src/axolotl/cli/preprocess.py
  src/axolotl/core/chat/__init__.py
  src/axolotl/core/chat/format/__init__.py
  src/axolotl/core/chat/format/chatml.py
  src/axolotl/core/chat/format/llama3x.py
  src/axolotl/core/chat/format/shared.py
  src/axolotl/core/chat/messages.py
  src/axolotl/core/datasets/__init__.py
  src/axolotl/core/datasets/chat.py
  src/axolotl/core/datasets/transforms/__init__.py
  src/axolotl/core/datasets/transforms/chat_builder.py
  src/axolotl/prompt_strategies/__init__.py
  src/axolotl/prompt_strategies/messages/__init__.py
  src/axolotl/prompt_strategies/messages/chat.py
  src/axolotl/prompt_tokenizers.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/sft.py
  tests/core/chat/__init__.py
  tests/core/chat/format/__init__.py
  tests/core/chat/test_messages.py
  tests/prompt_strategies/messages/__init__.py
  tests/prompt_strategies/messages/test_chat.py
Labels: wip

#1879 Reward model
  examples/gemma2/reward-model.yaml
  src/axolotl/core/trainer_builder.py
  src/axolotl/prompt_strategies/bradley_terry/README.md
  src/axolotl/prompt_strategies/bradley_terry/__init__.py
  src/axolotl/prompt_strategies/bradley_terry/chat_template.py
  src/axolotl/prompt_strategies/bradley_terry/llama3.py
  src/axolotl/prompt_strategies/chat_template.py
  src/axolotl/train.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/sft.py
  src/axolotl/utils/trainer.py
  tests/e2e/test_reward_model_llama.py
Labels: ready to merge

#1970 Feat: Add support for tokenizer’s or custom jinja chat_template
  README.md
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
  src/axolotl/cli/__init__.py
  src/axolotl/core/trainer_builder.py
  src/axolotl/prompt_strategies/bradley_terry/__init__.py
  src/axolotl/prompt_strategies/bradley_terry/chat_template.py
  src/axolotl/prompt_strategies/chat_template.py
  src/axolotl/prompt_strategies/dpo/chat_template.py
  src/axolotl/prompt_strategies/orpo/chat_template.py
  src/axolotl/prompt_strategies/sharegpt.py
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/config/__init__.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/models.py
  tests/prompt_strategies/test_chat_template_utils.py
  tests/prompt_strategies/test_chat_templates.py
  tests/prompt_strategies/test_chat_templates_advanced.py
  tests/prompt_strategies/test_dpo_chat_templates.py
  tests/test_validation_dataset.py
Labels: ready to merge

#1997 Hardware requirements
  README.md
Labels: documentation, ready to merge

#2001 feat: update yml chat_template to specify dataset field
  devtools/dev_chat_template.yml
  docs/debugging.qmd
  examples/deepseek-v2/qlora-fsdp-2_5.yaml
  examples/gemma2/qlora.yml
  examples/jamba/qlora_fsdp_large.yaml
  examples/llama-3/fft-8b-liger-fsdp.yaml
  examples/phi/lora-3.5.yaml
Labels: ready to merge

#1995 feat: add Exaone3 chat_template
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
Labels: ready to merge

#2003 Fix get_chat_template call for trainer builder
  src/axolotl/cli/__init__.py
  src/axolotl/core/trainer_builder.py
Labels: ready to merge

#2006 Add plugin manager's callback hooks to training flow
  src/axolotl/core/trainer_builder.py
  src/axolotl/integrations/base.py
Labels: ready to merge

#2007 add retries for load datasets requests failures
  src/axolotl/utils/data/sft.py
Labels: ready to merge
