Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-01, with the labels that each got.

#2231 Fixing OSX installation
  .pre-commit-config.yaml
  .pylintrc
  setup.py
  src/axolotl/utils/callbacks/lisa.py
  src/axolotl/utils/model_shard_quant.py
Labels: ready to merge

#2233 fix: mistral nemo does not recognize token_type_ids in forward
  src/axolotl/utils/trainer.py
Labels: ready to merge

#2247 add hf cache caching for GHA
  .github/workflows/tests.yml
  cicd/Dockerfile.jinja
  cicd/multigpu.py
  cicd/tests.py
Labels: ready to merge

#2242 update modal version for ci
  .github/workflows/multi-gpu-e2e.yml
  .github/workflows/tests-nightly.yml
  .github/workflows/tests.yml
Labels: ready to merge

#2235 feat: use SequentialSampler if `curriculum_sampling` is enabled with `sample_packing`
  src/axolotl/core/trainer_builder.py
Labels: ready to merge

#2238 feat: add support for data_files in pretraining
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2198 use 2.5.1 docker images as latest tag as it seems stable
  .github/workflows/main.yml
Labels: ready to merge

#2245 add helper to verify the correct model output file exists
  src/axolotl/cli/utils.py
  tests/e2e/integrations/test_cut_cross_entropy.py
  tests/e2e/integrations/test_liger.py
  tests/e2e/patched/test_4d_multipack_llama.py
  tests/e2e/patched/test_fa_xentropy.py
  tests/e2e/patched/test_falcon_samplepack.py
  tests/e2e/patched/test_fused_llama.py
  tests/e2e/patched/test_llama_s2_attention.py
  tests/e2e/patched/test_lora_llama_multipack.py
  tests/e2e/patched/test_mistral_samplepack.py
  tests/e2e/patched/test_mixtral_samplepack.py
  tests/e2e/patched/test_phi_multipack.py
  tests/e2e/patched/test_resume.py
  tests/e2e/patched/test_unsloth_qlora.py
  tests/e2e/test_dpo.py
  tests/e2e/test_embeddings_lr.py
  tests/e2e/test_falcon.py
  tests/e2e/test_llama.py
  tests/e2e/test_llama_pretrain.py
  tests/e2e/test_llama_vision.py
  tests/e2e/test_lora_llama.py
  tests/e2e/test_mamba.py
  tests/e2e/test_mistral.py
  tests/e2e/test_mixtral.py
  tests/e2e/test_optimizers.py
  tests/e2e/test_phi.py
  tests/e2e/test_relora_llama.py
  tests/e2e/test_reward_model_llama.py
  tests/e2e/utils.py
Labels: ready to merge

#2243 assume empty lora dropout means 0.0 and add tests
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  tests/test_lora.py
Labels: ready to merge

#2223 skip over rows in pretraining dataset
  docs/dataset-formats/pretraining.qmd
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2244 CLI cleanup and documentation
  scripts/finetune.py
  src/axolotl/cli/__init__.py
  src/axolotl/cli/args.py
  src/axolotl/cli/art.py
  src/axolotl/cli/checks.py
  src/axolotl/cli/config.py
  src/axolotl/cli/evaluate.py
  src/axolotl/cli/inference.py
  src/axolotl/cli/main.py
  src/axolotl/cli/merge_lora.py
  src/axolotl/cli/merge_sharded_fsdp_weights.py
  src/axolotl/cli/preprocess.py
  src/axolotl/cli/shard.py
  src/axolotl/cli/train.py
  src/axolotl/cli/utils.py
  src/axolotl/common/cli.py
  src/axolotl/common/datasets.py
  src/axolotl/evaluate.py
  src/axolotl/train.py
  src/axolotl/utils/data/sft.py
  tests/cli/conftest.py
  tests/cli/test_cli_fetch.py
  tests/cli/test_cli_inference.py
  tests/cli/test_cli_interface.py
  tests/cli/test_cli_merge_lora.py
  tests/cli/test_cli_merge_sharded_fsdp_weights.py
  tests/cli/test_cli_preprocess.py
  tests/cli/test_cli_shard.py
  tests/cli/test_cli_version.py
  tests/cli/test_utils.py
  tests/e2e/integrations/test_cut_cross_entropy.py
  tests/e2e/integrations/test_liger.py
  tests/e2e/patched/test_4d_multipack_llama.py
  tests/e2e/patched/test_cli_integrations.py
  tests/e2e/patched/test_fa_xentropy.py
  tests/e2e/patched/test_falcon_samplepack.py
  tests/e2e/patched/test_fused_llama.py
  tests/e2e/patched/test_llama_s2_attention.py
  tests/e2e/patched/test_lora_llama_multipack.py
  tests/e2e/patched/test_mistral_samplepack.py
  tests/e2e/patched/test_mixtral_samplepack.py
  tests/e2e/patched/test_model_patches.py
  tests/e2e/patched/test_phi_multipack.py
  tests/e2e/patched/test_resume.py
  tests/e2e/patched/test_unsloth_qlora.py
  tests/e2e/test_dpo.py
  tests/e2e/test_embeddings_lr.py
  tests/e2e/test_falcon.py
  tests/e2e/test_llama.py
  tests/e2e/test_llama_pretrain.py
  tests/e2e/test_llama_vision.py
  tests/e2e/test_lora_llama.py
  tests/e2e/test_mamba.py
  tests/e2e/test_mistral.py
  tests/e2e/test_mixtral.py
  tests/e2e/test_optimizers.py
  tests/e2e/test_packing_loss.py
  tests/e2e/test_phi.py
  tests/e2e/test_relora_llama.py
  tests/e2e/test_reward_model_llama.py
Labels: ready to merge

#2258 rename references to dpo dataset prep to pref data
  src/axolotl/common/datasets.py
  src/axolotl/utils/data/__init__.py
  src/axolotl/utils/data/rl.py
  tests/test_datasets.py
  tests/test_exact_deduplication.py
Labels: ready to merge

#2257 fix for indexing error inside torch.embeddings caused by num embeddings > num tokens in tokenizer
  src/axolotl/utils/models.py
Labels: ready to merge

#2263 option to not concatenate during pretraining
  docs/config.qmd
  src/axolotl/core/trainer_builder.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/pretraining.py
Labels: ready to merge

#2268 Add 5000 line history limit to tmux for docker cloud
  docker/Dockerfile-cloud
Labels: ready to merge

#2265 use the extracted field_messages to parse the role fields
  scripts/chat_datasets.py
Labels: bug, ready to merge

#2256 support for latest transformers release 4.48.1
  cicd/cicd.sh
  requirements.txt
  src/axolotl/core/trainer_builder.py
  src/axolotl/monkeypatch/trainer_grad_accum.py
  src/axolotl/monkeypatch/transformers_fa_utils.py
  src/axolotl/utils/models.py
  tests/e2e/multigpu/test_llama.py
  tests/e2e/patched/test_mixtral_samplepack.py
  tests/e2e/patched/test_model_patches.py
  tests/e2e/patched/test_unsloth_integration.py
  tests/e2e/solo/__init__.py
  tests/e2e/solo/test_relora_llama.py
  tests/patched/test_llama_trainer_ga.py
Labels: ready to merge, scheduled_release

#2272 chore(doc): fix explanation on gcs creds retrieval
  README.md
Labels: ready to merge

#2281 Take `split` param from config in all load_dataset instances
  src/axolotl/utils/data/shared.py
Labels: ready to merge

#2270 chore(doc): improve explanation for *_steps and *_strategy
  docs/config.qmd
Labels: ready to merge

#2213 support for custom lr groups for non-embedding modules
  docs/lr_groups.qmd
  src/axolotl/core/trainer_builder.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
Labels: ready to merge

#2289 bump bnb to 0.45.1
  requirements.txt
Labels: ready to merge

#2291 chore: refactor SaveModelCallback to stop handle fractional save_steps
  src/axolotl/utils/callbacks/__init__.py
Labels: ready to merge

#2282 Num epochs float
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/trainer.py
Labels: ready to merge

#2294 Removing torch 2.3.1
  .github/workflows/base.yml
  .github/workflows/main.yml
  .github/workflows/multi-gpu-e2e.yml
  .github/workflows/nightlies.yml
  .github/workflows/tests-nightly.yml
  .github/workflows/tests.yml
  README.md
  cicd/multigpu.py
  cicd/tests.py
  setup.py
  tests/e2e/patched/test_4d_multipack_llama.py
  tests/e2e/utils.py
Labels: ready to merge

#2251 Ray Train Axolotl Integration
  _quarto.yml
  cicd/Dockerfile.jinja
  docker/Dockerfile
  docs/images/ray-cluster-dashboard.png
  docs/ray-integration.qmd
  examples/llama-3/lora-1b-ray.yml
  setup.py
  src/axolotl/cli/args.py
  src/axolotl/cli/main.py
  src/axolotl/cli/train.py
  src/axolotl/train.py
  src/axolotl/utils/config/__init__.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  tests/e2e/multigpu/test_llama.py
  tests/e2e/multigpu/test_qwen2.py
  tests/e2e/multigpu/test_ray.py
Labels: enhancement, ready to merge, scheduled_release

#2237 native support for modal cloud from CLI
  README.md
  docs/cli.qmd
  examples/cloud/modal.yaml
  requirements.txt
  scripts/motd
  src/axolotl/cli/cloud/__init__.py
  src/axolotl/cli/cloud/base.py
  src/axolotl/cli/cloud/modal_.py
  src/axolotl/cli/main.py
  src/axolotl/integrations/lm_eval/__init__.py
  src/axolotl/integrations/lm_eval/args.py
  src/axolotl/integrations/lm_eval/cli.py
Labels: scheduled_release

#2295 refactor README; hardcode links to quarto docs; add additional quarto doc pages
  .github/CONTRIBUTING.md
  README.md
  _quarto.yml
  docs/dataset-formats/conversation.qmd
  docs/dataset-formats/stepwise_supervised.qmd
  docs/getting-started.qmd
  docs/inference.qmd
  docs/installation.qmd
  docs/multi-gpu.qmd
  styles.css
Labels: ready to merge
