Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-02, with the labels that each got.

#2171 [feature] sweeps
  src/axolotl/cli/main.py
  tests/cli/test_cli_sweeps.py
Labels: scheduled_release

#2211 fix: drop long seq even if not sample packing
  src/axolotl/prompt_strategies/bradley_terry/chat_template.py
  src/axolotl/utils/data/sft.py
  src/axolotl/utils/data/utils.py
  src/axolotl/utils/samplers/utils.py
  src/axolotl/utils/trainer.py
  tests/e2e/test_reward_model_smollm2.py
Labels: ready to merge

#2315 feat: update FA to 2.7.4.post1 which includes torch2.6 binary
  requirements.txt
Labels: ready to merge

#2304 feat(doc): Add multi-node torchrun info
  docs/multi-node.qmd
Labels: ready to merge

#2193 [Fixing #2149] load_from_disk for RL-type training
  src/axolotl/utils/data/rl.py
  src/axolotl/utils/data/sft.py
  src/axolotl/utils/data/shared.py
Labels: review requested

#2329 feat(doc): add tensorboard config to docs
  docs/config.qmd
Labels: ready to merge

#2322 Add `bos_token` and `add_generation_prompt` to the alpaca chat template
  src/axolotl/utils/chat_templates.py
Labels: ready to merge

#2260 feat: add config for optional parameters in a chat message
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
  docs/dataset-formats/index.qmd
  docs/faq.qmd
  docs/rlhf.qmd
  examples/deepseek-v2/qlora-fsdp-2_5.yaml
  examples/gemma2/qlora.yml
  examples/jamba/qlora_fsdp_large.yaml
  examples/llama-3/fft-8b-liger-fsdp.yaml
  examples/llama-3/instruct-dpo-lora-8b.yml
  examples/llama-3/instruct-lora-8b.yml
  examples/llama-3/lora-1b-deduplicate-dpo.yml
  examples/mistral/mistral-dpo-qlora.yml
  examples/phi/lora-3.5.yaml
  examples/qwen2/dpo.yaml
  scripts/chat_datasets.py
  src/axolotl/prompt_strategies/__init__.py
  src/axolotl/prompt_strategies/bradley_terry/chat_template.py
  src/axolotl/prompt_strategies/chat_template.py
  src/axolotl/prompt_strategies/dpo/chat_template.py
  src/axolotl/prompt_strategies/jinja_template_analyzer.py
  src/axolotl/prompt_strategies/messages/chat.py
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/config/__init__.py
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
  src/axolotl/utils/data/sft.py
  src/axolotl/utils/dict.py
  tests/e2e/integrations/test_kd.py
  tests/e2e/patched/test_fa_xentropy.py
  tests/e2e/solo/test_relora_llama.py
  tests/e2e/test_dpo.py
  tests/e2e/test_embeddings_lr.py
  tests/e2e/test_falcon.py
  tests/e2e/test_llama.py
  tests/e2e/test_llama_pretrain.py
  tests/e2e/test_llama_vision.py
  tests/e2e/test_lora_llama.py
  tests/e2e/test_mamba.py
  tests/e2e/test_mistral.py
  tests/e2e/test_mixtral.py
  tests/e2e/test_optimizers.py
  tests/e2e/test_packing_loss.py
  tests/e2e/test_phi.py
  tests/e2e/test_qwen.py
  tests/e2e/test_reward_model_smollm2.py
  tests/prompt_strategies/conftest.py
  tests/prompt_strategies/test_chat_templates.py
  tests/prompt_strategies/test_chat_templates_advanced.py
  tests/prompt_strategies/test_jinja_template_analyzer.py
  tests/test_validation_dataset.py
  tests/utils/test_models.py
Labels: ready to merge

#2309 chore: cleanup deprecated config elements
  src/axolotl/utils/config/models/input/v0_4_1/__init__.py
Labels: awaiting_rebase

#2344 Bumping 0.15.1 TRL version for GRPO+PEFT fix
  requirements.txt
  src/axolotl/core/trainers/grpo/trainer.py
Labels: ready to merge

#2339 fix(doc): add missing auto_find_batch_size
  docs/config.qmd
Labels: ready to merge

#2353 bump liger to 0.5.3
  requirements.txt
Labels: ready to merge

#2362 Fix(doc): address missing doc changes
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
  docs/dataset_preprocessing.qmd
  docs/faq.qmd
Labels: ready to merge
