Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-05, with the labels that each got.

#2622 include multipack support for qwen3 family
  src/axolotl/monkeypatch/multipack.py
Labels: ready to merge

#2628 fix dpo eval override to call grandparent instead of the broken super
  src/axolotl/core/trainers/dpo/trainer.py
Labels: ready to merge, scheduled_release

#2640 bump liger dep to 0.5.9
  requirements.txt
  setup.py
Labels: ready to merge, scheduled_release

#2613 feat(doc): add split_thinking docs
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
Labels: documentation, ready to merge, scheduled_release

#2617 allow plugins to return their own dataset
  src/axolotl/cli/preprocess.py
  src/axolotl/cli/train.py
  src/axolotl/integrations/base.py
  src/axolotl/train.py
  tests/e2e/integrations/test_hooks.py
Labels: ready to merge, scheduled_release

#2631 Multipack parallel bin packing
  src/axolotl/core/trainers/base.py
  src/axolotl/utils/samplers/multipack.py
Labels: ready to merge, scheduled_release

#2619 xformers attention with packing
  docs/config.qmd
  src/axolotl/core/trainer_builder.py
  src/axolotl/monkeypatch/attention/__init__.py
  src/axolotl/monkeypatch/attention/xformers.py
  src/axolotl/utils/callbacks/__init__.py
  src/axolotl/utils/config/__init__.py
  src/axolotl/utils/models.py
  src/axolotl/utils/schemas/config.py
Labels: scheduled_release

#2642 Add missing __init__.py file to `cut_cross_entropy` integration
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/__init__.py
Labels: ready to merge

#2621 Configurable embeddings upcast
  docs/config.qmd
  src/axolotl/monkeypatch/peft/__init__.py
  src/axolotl/monkeypatch/peft/utils.py
  src/axolotl/utils/models.py
  src/axolotl/utils/schemas/config.py
  tests/e2e/patched/test_peft_embeddings.py
Labels: scheduled_release

#2637 Fix: improve error message on failed dataset load
  src/axolotl/utils/data/shared.py
Labels: ready to merge

#2385 Add CAME Optimizer
  docs/config.qmd
  setup.py
  src/axolotl/core/trainer_builder.py
  src/axolotl/utils/schemas/enums.py
  src/axolotl/utils/schemas/training.py
  tests/e2e/test_optimizers.py
Labels: ready to merge

#2671 fix: remove doc string imports in monkeypatches
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/cohere.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/gemma.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/gemma3.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/llama.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/llama4.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/mistral3.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/qwen2_moe.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/qwen2_vl.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/qwen3_moe.py
  src/axolotl/integrations/liger/models/deepseekv2.py
  src/axolotl/integrations/liger/models/jamba.py
  src/axolotl/monkeypatch/gemma3.py
Labels: ready to merge

#2668 Make Axolotl Print Dataset Name Before Processing
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2675 Fix: Make MLflow config artifact logging respect hf_mlflow_log_artifa…
  src/axolotl/utils/callbacks/mlflow_.py
Labels: ready to merge

#2654 Fix for setting `adam_beta3` and `adam_epsilon2` for CAME Optimizer
  docs/config.qmd
  src/axolotl/core/trainer_builder.py
  src/axolotl/core/training_args.py
Labels: ready to merge

#2676 GRPO fixes (peft)
  cicd/multigpu.py
  src/axolotl/core/trainer_builder.py
  src/axolotl/core/trainers/grpo/trainer.py
  tests/e2e/multigpu/solo/test_grpo.py
Labels: ready to merge

#2696 feat: do not find turn indices if turn is not trainable
  src/axolotl/prompt_strategies/chat_template.py
Labels: ready to merge

#2706 feat(doc): note lora kernel incompat with RLHF
  docs/lora_optims.qmd
  src/axolotl/utils/schemas/config.py
Labels: ready to merge

#2724 fix: suppress non-axolotl logs unless it's warning or higher
  src/axolotl/logging_config.py
Labels: hold
