Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-06, with the labels that each got.

#2748 feat: add Group Relative Policy Optimization (GPRO) to RLHF documenta…
  docs/rlhf.qmd
Labels: documentation, ready to merge

#2749 feat(modal): update docker tag to use torch2.6 from torch2.5
  src/axolotl/cli/cloud/modal_.py
Labels: ready to merge

#2754 fix(deepspeed): deepspeed config not being set for z3
  src/axolotl/loaders/model.py
Labels: ready to merge

#2759 fix: remove hqq
  requirements.txt
Labels: ready to merge

#2773 handle when unable to save optimizer state when using ao optimizer with FSDP
  src/axolotl/core/trainers/base.py
  src/axolotl/core/trainers/mixins/__init__.py
  src/axolotl/core/trainers/mixins/checkpoints.py
Labels: ready to merge

#2739 Fix the bug of position ids padding
  src/axolotl/utils/collators/batching.py
Labels: ready to merge

#2774 Feat: add tool calling support via tools column
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
  src/axolotl/prompt_strategies/chat_template.py
  src/axolotl/utils/schemas/datasets.py
  tests/prompt_strategies/test_chat_templates_advanced.py
Labels: ready to merge

#2802 Fix: logging on py310
  docs/installation.qmd
  src/axolotl/logging_config.py
Labels: ready to merge

#2625 chunked cross entropy loss
  src/axolotl/integrations/cut_cross_entropy/__init__.py
  src/axolotl/loaders/patch_manager.py
  src/axolotl/monkeypatch/loss/__init__.py
  src/axolotl/monkeypatch/loss/chunked.py
  src/axolotl/utils/schemas/config.py
  tests/test_chunked_xentropy.py
Labels: ready to merge

#2832 fix(doc): default messages example used wrong key
  README.md
  docs/dataset-formats/conversation.qmd
Labels: documentation, ready to merge

#2766 Support --lora-on-cpu flag for DPO model merging
  src/axolotl/loaders/model.py
Labels: hold
