Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-04, with the labels that each got.

#2460 Release update 20250331
  .github/workflows/base.yml
  .github/workflows/main.yml
  .github/workflows/tests-nightly.yml
  .github/workflows/tests.yml
  requirements.txt
  src/axolotl/core/trainers/base.py
  src/axolotl/core/trainers/dpo/trainer.py
  src/axolotl/core/trainers/grpo/trainer.py
  src/axolotl/core/trainers/mixins/__init__.py
  src/axolotl/core/trainers/mixins/rng_state_loader.py
  src/axolotl/core/trainers/trl.py
  src/axolotl/utils/schemas/config.py
  tests/conftest.py
  tests/test_datasets.py
  tests/test_exact_deduplication.py
  tests/test_packed_batch_sampler.py
  tests/test_prompt_tokenizers.py
Labels: hold

#2462 Fix(doc): Minor doc changes for peft and modal
  docs/cli.qmd
  docs/config.qmd
Labels: ready to merge

#2461 Fix: remove the numerous sequential log
  docs/config.qmd
  src/axolotl/utils/samplers/multipack.py
Labels: ready to merge

#2472 feat: add support for multimodal in lora kernels
  docs/lora_optims.qmd
  src/axolotl/monkeypatch/lora_kernels.py
Labels: ready to merge

#2473 fix: gemma3 loss in forward pass
  src/axolotl/monkeypatch/gemma3.py
  src/axolotl/utils/models.py
Labels: ready to merge

#2470 fix: disable SP during merge
  src/axolotl/cli/merge_lora.py
Labels: ready to merge

#2471 fix: separate gemma3 text and vision example config
  examples/gemma3/gemma-3-4b-qlora.yml
  examples/gemma3/gemma-3-4b-vision-qlora.yml
Labels: ready to merge

#2475 fix(doc): document offload gradient_checkpointing option
  docs/config.qmd
Labels: ready to merge

#2500 fix: duplicate llama4 chattemplate enum
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/schemas/enums.py
Labels: ready to merge

#2497 add mocks for loading datasets in cli train tests
  tests/cli/test_cli_preprocess.py
  tests/cli/test_cli_train.py
Labels: ready to merge

#2516 Feat(examples): add deepcogito
  examples/deepcogito/cogito-v1-preview-llama-3B-lora.yml
  examples/deepcogito/cogito-v1-preview-qwen-14B-lora.yml
Labels: ready to merge

#2514 feat(doc): explain deepspeed configs
  docs/multi-gpu.qmd
Labels: ready to merge

#2509 chore: update doc links
  README.md
  docs/config.qmd
  docs/dataset-formats/index.qmd
  pyproject.toml
Labels: ready to merge

#2517 feat: add examples for deepcoder
  examples/deepcoder/deepcoder-14B-preview-lora.yml
Labels: ready to merge

#2524 make sure the all of the model is on the same device
  tests/e2e/patched/lora_kernels/test_lora_kernel_patching.py
Labels: ready to merge

#2521 feat: update cce to latest
  scripts/cutcrossentropy_install.py
  src/axolotl/integrations/cut_cross_entropy/README.md
  src/axolotl/integrations/cut_cross_entropy/__init__.py
Labels: ready to merge

#2503 fix: preprocess yielding whole dataset to each worker
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2532 fix(doc): cut cross entropy installation instructions broken in qmd
  src/axolotl/integrations/cut_cross_entropy/README.md
Labels: ready to merge

#2527 fix: upgrade liger to 0.5.8 and use native Gemma3 patches
  requirements.txt
  src/axolotl/integrations/liger/README.md
  src/axolotl/integrations/liger/__init__.py
Labels: ready to merge

#2536 prevent rate limiting to hf when using dispatch batches
  src/axolotl/utils/data/sft.py
  src/axolotl/utils/schemas/config.py
Labels: ready to merge

#2546 feat: add glm and glm4 multipack and cce
  examples/glm4/qlora-32b.yaml
  src/axolotl/integrations/cut_cross_entropy/README.md
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/glm4.py
  src/axolotl/integrations/cut_cross_entropy/monkeypatch/patch.py
  src/axolotl/monkeypatch/multipack.py
Labels: ready to merge

#2545 Fix(doc): add delinearize instruction
  docs/cli.qmd
  docs/installation.qmd
  examples/llama-4/README.md
Labels: ready to merge

#2564 don't fail on codecov upload for external contributor PRs
  cicd/cicd.sh
Labels: ready to merge

#2563 fix: gradient checkpointing functools.partial object has no attribute __self__
  src/axolotl/utils/gradient_checkpointing/__init__.py
Labels: ready to merge

#2559 chore(doc): minor update docker tags on doc
  docs/docker.qmd
Labels: ready to merge

#2558 fix: crash when pretraining_dataset with dispatch_batches is false
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2565 add e2e smoke test for using activation/gradient checkpointing with offload
  tests/e2e/patched/test_activation_checkpointing.py
Labels: ready to merge

#2573 fix(doc): clarify vllm usage with grpo
  docs/rlhf.qmd
Labels: ready to merge

#2570 replace references to random 68m model w 135m smollm2
  tests/conftest.py
  tests/e2e/patched/test_4d_multipack_llama.py
  tests/e2e/patched/test_fused_llama.py
  tests/e2e/patched/test_llama_s2_attention.py
  tests/e2e/patched/test_lora_llama_multipack.py
  tests/e2e/test_dpo.py
  tests/e2e/test_llama.py
  tests/e2e/test_load_model.py
  tests/e2e/test_lora_llama.py
  tests/e2e/test_optimizers.py
  tests/e2e/test_schedulers.py
  tests/test_normalize_config.py
  tests/utils/test_models.py
Labels: ready to merge

#2530 Add runpod sls handler
  .runpod/.gitignore
  .runpod/Dockerfile
  .runpod/README.md
  .runpod/hub.json
  .runpod/requirements.txt
  .runpod/src/config/config.yaml
  .runpod/src/handler.py
  .runpod/src/test_input.json
  .runpod/src/train.py
  .runpod/src/utils.py
  .runpod/tests.json
Labels: ready to merge

#2397 grab sys prompt too from dataset
  docs/config.qmd
  src/axolotl/prompt_strategies/chat_template.py
Labels: ready to merge

#2364 feat: add eos_tokens and train_on_eot for chat_template EOT parsing
  docs/config.qmd
  docs/dataset-formats/conversation.qmd
  docs/faq.qmd
  src/axolotl/integrations/kd/chat_template.py
  src/axolotl/prompt_strategies/chat_template.py
  src/axolotl/utils/schemas/config.py
  tests/prompt_strategies/test_chat_templates_advanced.py
Labels: ready to merge

#2432 add preview-docs workflow
  .github/workflows/preview-docs.yml
Labels: ready to merge

#2572 support val_set_size for splitting test split from train with DPO
  src/axolotl/core/trainers/dpo/trainer.py
  src/axolotl/utils/data/rl.py
Labels: ready to merge

#2575 fix(doc): update key used to point to url in multimodal doc
  docs/multimodal.qmd
Labels: documentation, ready to merge

#2584 Plugins create_lr_scheduler support
  src/axolotl/core/trainers/mixins/scheduler.py
  src/axolotl/core/trainers/relora.py
  src/axolotl/integrations/base.py
  tests/e2e/integrations/test_hooks.py
Labels: plugins

#2595 patch to convert LR from tensor to float when using DS
  src/axolotl/core/trainer_builder.py
  src/axolotl/monkeypatch/trainer/lr.py
Labels: ready to merge

#2596 feat: add qwen3 moe block for ds3
  src/axolotl/common/architectures.py
Labels: ready to merge

#2593 upload the deepspeed json to wandb
  src/axolotl/utils/callbacks/__init__.py
Labels: ready to merge

#2591 Handle other reasoning trace dataset formats
  src/axolotl/prompt_strategies/chat_template.py
  tests/prompt_strategies/test_chat_templates_thinking.py
Labels: ready to merge, datasets

#2597 only import vllm serve cli if its being called
  src/axolotl/cli/main.py
Labels: ready to merge

#2592 replace zero_only with simpler if statement
  .github/workflows/multi-gpu-e2e.yml
  .github/workflows/tests.yml
  src/axolotl/integrations/cut_cross_entropy/__init__.py
  src/axolotl/integrations/liger/__init__.py
  src/axolotl/utils/distributed.py
  src/axolotl/utils/models.py
Labels: ready to merge

#2598 additional args for grpo config/trainer
  src/axolotl/core/trainers/grpo/__init__.py
  src/axolotl/utils/schemas/config.py
  src/axolotl/utils/schemas/trl.py
Labels: ready to merge
