Repository axolotl-ai-cloud/axolotl, pull requests merged in 2025-07, with the labels that each got.

#2849 Decouple generate_during_eval from wandb to support other visualizers
  src/axolotl/core/trainers/dpo/__init__.py
  src/axolotl/utils/schemas/config.py
Labels: ready to merge

#2845 Fix: tokenize stall due to not shuffling dataset
  src/axolotl/utils/data/shared.py
Labels: ready to merge

#2867 build fa2 from source for base image with torch2.6 and cu124
  .github/workflows/base.yml
  docker/Dockerfile-base
Labels: scheduled_release

#2866 respect shuffle_merged_datasets for single dataset too
  src/axolotl/utils/data/shared.py
Labels: ready to merge, scheduled_release

#2862 don't use tokenizer parallelism when using packing
  src/axolotl/utils/trainer.py
Labels: ready to merge, scheduled_release

#2632 setup defaults for dataloader to ensure GPU is kept busy
  src/axolotl/utils/schemas/config.py
  tests/patched/test_validation.py
Labels: ready to merge, scheduled_release

#2795 manage jinja templates as nicely formatted files
  MANIFEST.in
  src/axolotl/utils/chat_templates.py
  src/axolotl/utils/chat_templates/__init__.py
  src/axolotl/utils/chat_templates/base.py
  src/axolotl/utils/chat_templates/templates/alpaca.jinja
  src/axolotl/utils/chat_templates/templates/aya.jinja
  src/axolotl/utils/chat_templates/templates/chatml.jinja
  src/axolotl/utils/chat_templates/templates/cohere.jinja
  src/axolotl/utils/chat_templates/templates/command_a.jinja
  src/axolotl/utils/chat_templates/templates/command_a_rag.jinja
  src/axolotl/utils/chat_templates/templates/command_a_tool_use.jinja
  src/axolotl/utils/chat_templates/templates/deepseek_v2.jinja
  src/axolotl/utils/chat_templates/templates/deepseek_v3.jinja
  src/axolotl/utils/chat_templates/templates/exaone.jinja
  src/axolotl/utils/chat_templates/templates/falcon_h1.jinja
  src/axolotl/utils/chat_templates/templates/gemma.jinja
  src/axolotl/utils/chat_templates/templates/gemma3.jinja
  src/axolotl/utils/chat_templates/templates/jamba.jinja
  src/axolotl/utils/chat_templates/templates/llama3.jinja
  src/axolotl/utils/chat_templates/templates/llama3_2_vision.jinja
  src/axolotl/utils/chat_templates/templates/llama4.jinja
  src/axolotl/utils/chat_templates/templates/llava.jinja
  src/axolotl/utils/chat_templates/templates/metharme.jinja
  src/axolotl/utils/chat_templates/templates/mistral_v1.jinja
  src/axolotl/utils/chat_templates/templates/mistral_v2v3.jinja
  src/axolotl/utils/chat_templates/templates/mistral_v3_tekken.jinja
  src/axolotl/utils/chat_templates/templates/mistral_v7_tekken.jinja
  src/axolotl/utils/chat_templates/templates/phi_3.jinja
  src/axolotl/utils/chat_templates/templates/phi_35.jinja
  src/axolotl/utils/chat_templates/templates/phi_4.jinja
  src/axolotl/utils/chat_templates/templates/pixtral.jinja
  src/axolotl/utils/chat_templates/templates/qwen2_vl.jinja
  src/axolotl/utils/chat_templates/templates/qwen3.jinja
  src/axolotl/utils/chat_templates/templates/qwen_25.jinja
  src/axolotl/utils/schemas/config.py
  src/axolotl/utils/schemas/datasets.py
Labels: scheduled_release

#2865 TiledMLP support
  src/axolotl/loaders/patch_manager.py
  src/axolotl/monkeypatch/tiled_mlp.py
  src/axolotl/utils/schemas/config.py
  src/axolotl/utils/schemas/validation.py
Labels: scheduled_release

#2868 densemixer plugin integration
  docs/custom_integrations.qmd
  src/axolotl/integrations/densemixer/README.md
  src/axolotl/integrations/densemixer/__init__.py
  src/axolotl/integrations/densemixer/args.py
  src/axolotl/integrations/densemixer/plugin.py
Labels: scheduled_release

#2879 Fix link in FSDP + QLoRA docs.
  docs/fsdp_qlora.qmd
Labels: ready to merge

#2859 fix: set add_generation_prompt to False when apply chat template for multimodal
  src/axolotl/utils/collators/mm_chat.py
Labels: ready to merge, scheduled_release

#2894 fix: customized dataset with simpo
  docs/rlhf.qmd
  src/axolotl/prompt_strategies/dpo/user_defined.py
  src/axolotl/utils/config/__init__.py
Labels: ready to merge

#2905 Liquid Foundation Model 2 support
  examples/lfm2/README.md
  examples/lfm2/lfm2-350m-fft.yaml
Labels: ready to merge

#2915 fix ddp for incorrect steps
  src/axolotl/utils/config/__init__.py
  tests/test_train.py
Labels: bug, hotfix

#2892 upgrade trl==0.19.1
  .github/workflows/multi-gpu-e2e.yml
  requirements.txt
  src/axolotl/cli/vllm_serve.py
  src/axolotl/core/trainers/grpo/__init__.py
  src/axolotl/core/trainers/grpo/trainer.py
  src/axolotl/utils/schemas/trl.py
  src/axolotl/utils/schemas/vllm.py
  tests/e2e/multigpu/solo/test_grpo.py
  tests/e2e/multigpu/test_llama.py
Labels: ready to merge

#2893 upgrade liger to 0.6.0
  requirements.txt
Labels: ready to merge

#2916 fix xformers version for python 2.6
  setup.py
Labels: ready to merge

#2921 update nightlies builds
  .github/workflows/nightlies.yml
Labels: ready to merge

#2898 feat: add call method to mistral tokenizer wrapper
  src/axolotl/utils/mistral_tokenizer.py
  tests/prompt_strategies/test_chat_templates_mistral.py
Labels: ready to merge

#2918 Improve Dataset Processing Multiprocessing, Sharding, and Qwen Tokenizer Bug Fix.
  src/axolotl/core/datasets/chat.py
  src/axolotl/datasets.py
  src/axolotl/loaders/tokenizer.py
  src/axolotl/utils/config/__init__.py
  src/axolotl/utils/data/shared.py
  src/axolotl/utils/schemas/config.py
Labels: ready to merge

#2945 Add torchtitan link to FSDP migration
  docs/multi-gpu.qmd
Labels: ready to merge

#2958 fix(log): suppress warning if we enabled skip prepare
  src/axolotl/utils/data/sft.py
Labels: ready to merge

#2966 handle refactor upstream for flash attention
  src/axolotl/monkeypatch/ring_attn/patch.py
Labels: ready to merge

#2968 upgrade torchao to latest
  requirements.txt
Labels: ready to merge

#2972 feat(doc): add all providers to readme
  README.md
  docs/installation.qmd
Labels: ready to merge

#2985 don't publish to netlify on contributor submissions since it requires…
  .github/workflows/preview-docs.yml
  docker/Dockerfile-cloud-no-tmux
  scripts/motd
Labels: ready to merge

#2988 Use '<|finetune_right_pad|>' as padding token for LLama4
  examples/llama-4/do-no-use-fa2/maverick-qlora-fsdp1.yaml
  examples/llama-4/do-no-use-fa2/scout-qlora-fsdp1.yaml
  examples/llama-4/do-no-use-fa2/scout-qlora-single-h100.yaml
  examples/llama-4/do-no-use-fa2/scout-vision-qlora-fsdp.yaml
  examples/llama-4/scout-qlora-flexattn-fsdp2.yaml
  examples/llama-4/scout-qlora-single-h100-flex.yaml
  examples/llama-4/scout-vision-qlora-fsdp2-flex.yaml
Labels: ready to merge

#1680 jagged lr restart scheudler
  _quarto.yml
  examples/llama-2/relora.yml
  src/axolotl/core/builders/causal.py
  src/axolotl/core/trainers/__init__.py
  src/axolotl/core/trainers/mixins/scheduler.py
  src/axolotl/core/trainers/relora.py
  src/axolotl/core/training_args_base.py
  src/axolotl/monkeypatch/relora.py
  src/axolotl/train.py
  src/axolotl/utils/schedulers.py
  src/axolotl/utils/schemas/config.py
  src/axolotl/utils/schemas/peft.py
  src/axolotl/utils/schemas/training.py
  src/axolotl/utils/schemas/validation.py
  tests/e2e/solo/test_relora_llama.py
Labels: enhancement, review requested
